
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class SyncWidget
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox3;
		private global::WidgetLibrary.DragDropWidget DragDropWidget;
		private global::Gtk.FileChooserWidget filechooserwidget1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Statusbar statusbar1;
		private global::Gtk.ProgressBar progressbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.SyncWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w2, 0);
			this.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.Name = "WidgetLibrary.SyncWidget";
			// Container child WidgetLibrary.SyncWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.DragDropWidget = new global::WidgetLibrary.DragDropWidget ();
			this.DragDropWidget.Events = ((global::Gdk.EventMask)(256));
			this.DragDropWidget.Name = "DragDropWidget";
			this.hbox3.Add (this.DragDropWidget);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.DragDropWidget]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.filechooserwidget1 = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(0)));
			this.filechooserwidget1.Name = "filechooserwidget1";
			this.hbox3.Add (this.filechooserwidget1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.filechooserwidget1]));
			w4.Position = 1;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.statusbar1.HasResizeGrip = false;
			this.hbox2.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.statusbar1]));
			w6.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.Name = "progressbar1";
			this.hbox2.Add (this.progressbar1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.progressbar1]));
			w7.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.DragDropWidget.DragDataReceived += new global::Gtk.DragDataReceivedHandler (this.OnDragDropWidgetDragDataReceived);
			this.DragDropWidget.DragDrop += new global::Gtk.DragDropHandler (this.OnDragDropWidgetDragDrop);
			this.DragDropWidget.DragDataGet += new global::Gtk.DragDataGetHandler (this.OnDragDropWidgetDragDataGet);
			this.DragDropWidget.DragEnd += new global::Gtk.DragEndHandler (this.OnDragDropWidgetDragEnd);
		}
	}
}
