
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class SyncWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.SyncWindow
			this.Name = "WidgetLibrary.SyncWindow";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 432;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
