
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class PiDataSelectionWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.PiDataSelectionWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetLibrary.PiDataSelectionWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
