
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class ChoosenFilesWidget
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.ToggleButton SelectAllToggleButton;
		private global::Gtk.Button RemoveButton;
		private global::Gtk.HBox hbox1;
		private global::Gtk.HBox hbox4;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView FileTreeView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.ChoosenFilesWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetLibrary.ChoosenFilesWidget";
			// Container child WidgetLibrary.ChoosenFilesWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.SelectAllToggleButton = new global::Gtk.ToggleButton ();
			this.SelectAllToggleButton.CanFocus = true;
			this.SelectAllToggleButton.Name = "SelectAllToggleButton";
			this.SelectAllToggleButton.UseUnderline = true;
			this.SelectAllToggleButton.Label = global::Mono.Unix.Catalog.GetString ("Select All");
			this.hbox2.Add (this.SelectAllToggleButton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.SelectAllToggleButton]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.RemoveButton = new global::Gtk.Button ();
			this.RemoveButton.CanFocus = true;
			this.RemoveButton.Name = "RemoveButton";
			this.RemoveButton.UseUnderline = true;
			this.RemoveButton.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			this.hbox2.Add (this.RemoveButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.RemoveButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.FileTreeView = new global::Gtk.TreeView ();
			this.FileTreeView.CanFocus = true;
			this.FileTreeView.Name = "FileTreeView";
			this.GtkScrolledWindow.Add (this.FileTreeView);
			this.hbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.GtkScrolledWindow]));
			w5.Position = 0;
			this.hbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
			w6.Position = 0;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w7.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
