
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class SyncWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox vbox2;
		private global::Gtk.TreeView devicesTreeView;
		private global::Gtk.Table table3;
		private global::Gtk.Button connectButton;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.CheckButton standardRaspCheckbutton;
		private global::Gtk.Statusbar SyncStatusBar;
		private global::Gtk.ProgressBar SyncProgressBar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.SyncWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "WidgetLibrary.SyncWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SyncWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child WidgetLibrary.SyncWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.devicesTreeView = new global::Gtk.TreeView ();
			this.devicesTreeView.CanFocus = true;
			this.devicesTreeView.Name = "devicesTreeView";
			this.vbox2.Add (this.devicesTreeView);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.devicesTreeView]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.connectButton = new global::Gtk.Button ();
			this.connectButton.CanFocus = true;
			this.connectButton.Name = "connectButton";
			this.connectButton.UseUnderline = true;
			this.connectButton.Label = global::Mono.Unix.Catalog.GetString ("connect");
			this.table3.Add (this.connectButton);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.connectButton]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.table3.Add (this.fixed2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed2]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.standardRaspCheckbutton = new global::Gtk.CheckButton ();
			this.standardRaspCheckbutton.CanFocus = true;
			this.standardRaspCheckbutton.Name = "standardRaspCheckbutton";
			this.standardRaspCheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Raspberry als Standard festlegen");
			this.standardRaspCheckbutton.DrawIndicator = true;
			this.standardRaspCheckbutton.UseUnderline = true;
			this.table3.Add (this.standardRaspCheckbutton);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.standardRaspCheckbutton]));
			w5.XOptions = ((global::Gtk.AttachOptions)(1));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.SyncStatusBar = new global::Gtk.Statusbar ();
			this.SyncStatusBar.Name = "SyncStatusBar";
			this.SyncStatusBar.Spacing = 6;
			// Container child SyncStatusBar.Gtk.Box+BoxChild
			this.SyncProgressBar = new global::Gtk.ProgressBar ();
			this.SyncProgressBar.Name = "SyncProgressBar";
			this.SyncStatusBar.Add (this.SyncProgressBar);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.SyncStatusBar [this.SyncProgressBar]));
			w7.Position = 1;
			this.vbox2.Add (this.SyncStatusBar);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.SyncStatusBar]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 432;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
