
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class RaspberrySelection
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.TreeView devicesTreeView;
		private global::Gtk.Table table2;
		private global::Gtk.CheckButton alwaysSyncCheckBox;
		private global::Gtk.Button connectButton;
		private global::Gtk.Fixed fixed1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.RaspberrySelection
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetLibrary.RaspberrySelection";
			// Container child WidgetLibrary.RaspberrySelection.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.devicesTreeView = new global::Gtk.TreeView ();
			this.devicesTreeView.CanFocus = true;
			this.devicesTreeView.Name = "devicesTreeView";
			this.vbox1.Add (this.devicesTreeView);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.devicesTreeView]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.alwaysSyncCheckBox = new global::Gtk.CheckButton ();
			this.alwaysSyncCheckBox.CanFocus = true;
			this.alwaysSyncCheckBox.Name = "alwaysSyncCheckBox";
			this.alwaysSyncCheckBox.Label = global::Mono.Unix.Catalog.GetString ("use this Raspberry as standard");
			this.alwaysSyncCheckBox.DrawIndicator = true;
			this.table2.Add (this.alwaysSyncCheckBox);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.alwaysSyncCheckBox]));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.connectButton = new global::Gtk.Button ();
			this.connectButton.CanFocus = true;
			this.connectButton.Name = "connectButton";
			this.connectButton.UseUnderline = true;
			// Container child connectButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-connect", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("connect");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.connectButton.Add (w3);
			this.table2.Add (this.connectButton);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.connectButton]));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.table2.Add (this.fixed1);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed1]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table2]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
