
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class RaspberrySelect
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.ToggleButton AutoSyncToggleButton;
		private global::Gtk.Button ManualSyncButton;
		private global::Gtk.Button PCButton;
		private global::Gtk.Button PIButton;
		private global::Gtk.ToggleButton SpecialSyncToggleButton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.RaspberrySelect
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetLibrary.RaspberrySelect";
			// Container child WidgetLibrary.RaspberrySelect.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.AutoSyncToggleButton = new global::Gtk.ToggleButton ();
			this.AutoSyncToggleButton.CanFocus = true;
			this.AutoSyncToggleButton.Name = "AutoSyncToggleButton";
			this.AutoSyncToggleButton.UseUnderline = true;
			this.AutoSyncToggleButton.Label = global::Mono.Unix.Catalog.GetString ("AutoSync");
			this.hbox1.Add (this.AutoSyncToggleButton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.AutoSyncToggleButton]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ManualSyncButton = new global::Gtk.Button ();
			this.ManualSyncButton.CanFocus = true;
			this.ManualSyncButton.Name = "ManualSyncButton";
			this.ManualSyncButton.UseUnderline = true;
			this.ManualSyncButton.Label = global::Mono.Unix.Catalog.GetString ("Synchronize");
			this.hbox1.Add (this.ManualSyncButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ManualSyncButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.PCButton = new global::Gtk.Button ();
			this.PCButton.CanFocus = true;
			this.PCButton.Name = "PCButton";
			this.PCButton.UseUnderline = true;
			this.PCButton.Label = global::Mono.Unix.Catalog.GetString ("PC");
			this.hbox1.Add (this.PCButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PCButton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.PIButton = new global::Gtk.Button ();
			this.PIButton.CanFocus = true;
			this.PIButton.Name = "PIButton";
			this.PIButton.UseUnderline = true;
			this.PIButton.Label = global::Mono.Unix.Catalog.GetString ("RaspberryPi");
			this.hbox1.Add (this.PIButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PIButton]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.SpecialSyncToggleButton = new global::Gtk.ToggleButton ();
			this.SpecialSyncToggleButton.CanFocus = true;
			this.SpecialSyncToggleButton.Name = "SpecialSyncToggleButton";
			this.SpecialSyncToggleButton.UseUnderline = true;
			this.SpecialSyncToggleButton.Label = global::Mono.Unix.Catalog.GetString ("SpecialSync");
			this.hbox1.Add (this.SpecialSyncToggleButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.SpecialSyncToggleButton]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
