
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class RaspberrySelect
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.TreeView devicesTreeView;
		private global::Gtk.Table table3;
		private global::Gtk.Button connectButton;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.CheckButton standardRaspCheckbutton;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.RaspberrySelect
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetLibrary.RaspberrySelect";
			// Container child WidgetLibrary.RaspberrySelect.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.devicesTreeView = new global::Gtk.TreeView ();
			this.devicesTreeView.CanFocus = true;
			this.devicesTreeView.Name = "devicesTreeView";
			this.vbox2.Add (this.devicesTreeView);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.devicesTreeView]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.connectButton = new global::Gtk.Button ();
			this.connectButton.CanFocus = true;
			this.connectButton.Name = "connectButton";
			this.connectButton.UseUnderline = true;
			this.connectButton.Label = global::Mono.Unix.Catalog.GetString ("connect");
			this.table3.Add (this.connectButton);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.connectButton]));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.table3.Add (this.fixed2);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed2]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.standardRaspCheckbutton = new global::Gtk.CheckButton ();
			this.standardRaspCheckbutton.CanFocus = true;
			this.standardRaspCheckbutton.Name = "standardRaspCheckbutton";
			this.standardRaspCheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Raspberry als Standard festlegen");
			this.standardRaspCheckbutton.DrawIndicator = true;
			this.standardRaspCheckbutton.UseUnderline = true;
			this.table3.Add (this.standardRaspCheckbutton);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.standardRaspCheckbutton]));
			w4.XOptions = ((global::Gtk.AttachOptions)(1));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
