
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class RaspberrySelection
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.TreeView devicesTreeView;
		private global::Gtk.Table table1;
		private global::Gtk.Button connectButton;
		private global::Gtk.CheckButton fixConnectCheckbutton;
		private global::Gtk.Fixed fixed1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.RaspberrySelection
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetLibrary.RaspberrySelection";
			// Container child WidgetLibrary.RaspberrySelection.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Homogeneous = true;
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.devicesTreeView = new global::Gtk.TreeView ();
			this.devicesTreeView.CanFocus = true;
			this.devicesTreeView.Name = "devicesTreeView";
			this.vbox1.Add (this.devicesTreeView);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.devicesTreeView]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.connectButton = new global::Gtk.Button ();
			this.connectButton.CanFocus = true;
			this.connectButton.Name = "connectButton";
			this.connectButton.UseUnderline = true;
			this.connectButton.Label = global::Mono.Unix.Catalog.GetString ("connect");
			this.table1.Add (this.connectButton);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.connectButton]));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.fixConnectCheckbutton = new global::Gtk.CheckButton ();
			this.fixConnectCheckbutton.CanFocus = true;
			this.fixConnectCheckbutton.Name = "fixConnectCheckbutton";
			this.fixConnectCheckbutton.Label = global::Mono.Unix.Catalog.GetString ("als Standard auswählen");
			this.fixConnectCheckbutton.DrawIndicator = true;
			this.fixConnectCheckbutton.UseUnderline = true;
			this.table1.Add (this.fixConnectCheckbutton);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixConnectCheckbutton]));
			w3.XOptions = ((global::Gtk.AttachOptions)(0));
			w3.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.table1.Add (this.fixed1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed1]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
