
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class RaspberrySelect
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.RaspberrySelect
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetLibrary.RaspberrySelect";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
