
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetLibrary
{
	public partial class SyncWidget
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ToggleButton AutoSyncToggleButton;
		private global::Gtk.Button ManSyncButton;
		private global::Gtk.Button SpecialSyncButton;
		private global::Gtk.Button ComputerButton;
		private global::Gtk.Button RaspberryButton;
		private global::Gtk.HBox hbox3;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Statusbar statusbar1;
		private global::Gtk.ProgressBar progressbar1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetLibrary.SyncWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "WidgetLibrary.SyncWidget";
			// Container child WidgetLibrary.SyncWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'/></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.AutoSyncToggleButton = new global::Gtk.ToggleButton ();
			this.AutoSyncToggleButton.CanFocus = true;
			this.AutoSyncToggleButton.Name = "AutoSyncToggleButton";
			this.AutoSyncToggleButton.UseUnderline = true;
			this.AutoSyncToggleButton.Label = global::Mono.Unix.Catalog.GetString ("AutoSync");
			this.hbox1.Add (this.AutoSyncToggleButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.AutoSyncToggleButton]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ManSyncButton = new global::Gtk.Button ();
			this.ManSyncButton.CanFocus = true;
			this.ManSyncButton.Name = "ManSyncButton";
			this.ManSyncButton.UseUnderline = true;
			this.ManSyncButton.Label = global::Mono.Unix.Catalog.GetString ("ManSync");
			this.hbox1.Add (this.ManSyncButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ManSyncButton]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.SpecialSyncButton = new global::Gtk.Button ();
			this.SpecialSyncButton.CanFocus = true;
			this.SpecialSyncButton.Name = "SpecialSyncButton";
			this.SpecialSyncButton.UseUnderline = true;
			this.SpecialSyncButton.Label = global::Mono.Unix.Catalog.GetString ("SpecialSync");
			this.hbox1.Add (this.SpecialSyncButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.SpecialSyncButton]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ComputerButton = new global::Gtk.Button ();
			this.ComputerButton.CanFocus = true;
			this.ComputerButton.Name = "ComputerButton";
			this.ComputerButton.UseUnderline = true;
			this.ComputerButton.Label = global::Mono.Unix.Catalog.GetString ("Computer");
			this.hbox1.Add (this.ComputerButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ComputerButton]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.RaspberryButton = new global::Gtk.Button ();
			this.RaspberryButton.CanFocus = true;
			this.RaspberryButton.Name = "RaspberryButton";
			this.RaspberryButton.UseUnderline = true;
			this.RaspberryButton.Label = global::Mono.Unix.Catalog.GetString ("Raspberry");
			this.hbox1.Add (this.RaspberryButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.RaspberryButton]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w10.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.hbox2.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.statusbar1]));
			w11.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.Name = "progressbar1";
			this.hbox2.Add (this.progressbar1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.progressbar1]));
			w12.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
