//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace WidgetLibrary
{
	[System.ComponentModel.ToolboxItem(true)]
	public partial class PiDataSelectionWidget : Gtk.Bin
	{
		public PiDataSelectionWidget ()
		{
			this.Build ();
		}
	}
}

