//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Gtk;

namespace WidgetLibrary
{
	[System.ComponentModel.ToolboxItem(true)]
	public partial class SyncWidget : Gtk.Bin
	{
		public SyncWidget ()
		{
			this.Build ();

		}

		protected void OnDragDropWidgetDragDataReceived (object o, Gtk.DragDataReceivedArgs args)
		{
			MessageDialog md = new MessageDialog (null, DialogFlags.DestroyWithParent, MessageType.Info, ButtonsType.Ok, "Funktioniert!!!");
			md.Run ();
			md.Destroy ();
		}

		protected void OnDragDropWidgetDragDrop (object o, DragDropArgs args)
		{
			MessageDialog md = new MessageDialog (null, DialogFlags.DestroyWithParent, MessageType.Info, ButtonsType.Ok, "Funktioniert!!!");
			md.Run ();
			md.Destroy ();
		}

		protected void OnDragDropWidgetDragDataGet (object o, DragDataGetArgs args)
		{
			MessageDialog md = new MessageDialog (null, DialogFlags.DestroyWithParent, MessageType.Info, ButtonsType.Ok, "Funktioniert!!!");
			md.Run ();
			md.Destroy ();
		}




		protected void OnDragDropWidgetDragEnd (object o, DragEndArgs args)
		{
			MessageDialog md = new MessageDialog (null, DialogFlags.DestroyWithParent, MessageType.Info, ButtonsType.Ok, "Funktioniert!!!");
			md.Run ();
			md.Destroy ();
		}
	}
}

