
// This file has been generated by the GUI designer. Do not modify.
namespace syncsoft
{
	public partial class RSelectionWindow
	{
		private global::WidgetLibrary.RaspberrySelection raspberryselection1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget syncsoft.RSelectionWindow
			this.Name = "syncsoft.RSelectionWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("RSelectionWindow");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-connect", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child syncsoft.RSelectionWindow.Gtk.Container+ContainerChild
			this.raspberryselection1 = new global::WidgetLibrary.RaspberrySelection ();
			this.raspberryselection1.Events = ((global::Gdk.EventMask)(256));
			this.raspberryselection1.Name = "raspberryselection1";
			this.Add (this.raspberryselection1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
